### PR TITLE
Generate markdown

### LINKED ISSUE #18: Support multiple output formats
Formats to support:
- [x] Terraform
- [x] CSV (single ACL) - table schema as in [here](https://cloud.ibm.com/docs/vpc?topic=vpc-using-acls#acl1-example-rules)
- [x] CSV (multiple ACLs) - the appropriate format needs to be decided
- [ ] md - same table schema

### PR DESCRIPTION
**Pull request by elazarg**
Fix #18

### CODE REVIEW

**Comment by kyorav** [comment]
I think we need to change the headers for SG generation (for CSV output as well) as they are very confusing to me. I would replace "Target Type" with "Remote Endpoint", "Target" with "Ports", and "Value" with "Explanation". I'd also prefer to move "Remote Endpoint" to immediately after "Direction".

I remember you drew inspiration for the format from someplace, can you post the link here for reference?

**Comment by elazarg** [comment]
> I remember you drew inspiration for the format from someplace, can you post the link here for reference?

There's no link; it's based on the CSV/xlsx format downloadable from IBM cloud for each resource and direction separately. Here's an example:

|Protocol | Source type | Source | Value
|-- | -- | -- | --
|TCP | IP address | 192.168.1.2 | Ports 2-4
|ICMP | CIDR block | 192.168.0.0/24 | Type: 1, Code: 2

Replacing `Target` with `Remote` and `Target type` with `Remote type` is a good idea.

> and "Value" with "Explanation".

Did you mean "Description"?

We can have different names for MD and CSV, but it can also be confusing.

**Comment by kyorav** [comment]
OK, lets ignore the IBM download thing, it operates in a totally different context.

"Description" is fine. I couldn't think of a concise title that would tell you that this is where you get information about why we created this rule.

The MD and CSV have the same information and should therefore have the same header line.

**Review by kyorav — CHANGES_REQUESTED** [review]
The CSV headers are fine. 
Change the MD headers to match the CSV headers.

**Review by kyorav — APPROVED** [review]
ignore previous review, it was based on VSCODE's erroneous markdown preview.

**Pull request merged**
